# Vanilla

## Creation of the graph (neural network)

### Para ANN (Implmentacion grafo)


In [ ]:
def create_ann(w_img, h_img, num_hlayers, neurons_per_hlayer, num_results):
    len_layer1 = w_img * h_img
    g = {}
    #Notacion que quiero usar el nombre va a ser: l_n -> siendo l el numero de layer y n el numero de neurona en ese layer.
    for i in range(len_layer1):
        xd = "0_" + str(i)
        g[xd] = []
        
    for hlay in range(num_hlayers):
        for neuron in neurons_per_hlayer:
            xd = str(hlay+1) + "_" + str(neuron)
            g[xd] = []
            
    for i in range(num_results):
        xd = str(1+num_hlayers) + str(i)
        g[xd] = []
        
    
    # Las conexiones van a ser (i, w, f) -> I: inicial, W: peso, F:final.
    
    for layer in range(num_hlayers+2):
        if layer == 0:
            for neuron in range(w_img*h_img):
                xd1 = "0_" + str(neuron)
                for next_n in range(neurons_per_hlayer):
                    xd2="1_" + str(next_n)
                    g[xd1]=(xd1, 0, xd2)
                
        if layer != 0 and layer != (num_hlayers+1) and layer != num_hlayers:
            for neuron in range(neurons_per_hlayer):
                xd1 = str(layer) + "_" + str(neuron)
                for next_n in range(neurons_per_hlayer):
                    xd2 = str(layer+1) + "_" + str(next_n)
                    g[xd1] = (xd1, 0, xd2)
                    
                    
                    #Softmax -> mc
                    #sigmoide -> bin
                    #identidad / linear -> regression

In [ ]:
class Neuron:
    pos = ()
    
    def __init__(self, pos):
        self.pos = pos
        
    def summ_junction(self, ):
        pass
        
    def relu(self, x):
        if x > 0:
            return 0
        elif x<=0:
            return x
        else:
            print("Esto no debio haber pasado... ")

In [ ]:
class Network:
    def __init__(self, w_img, h_img, num_hlayers, neurons_per_hlayer, num_results):
        network = {}
        l0 = w_img * h_img #TODO: Crear la capa 0
        for i in range(num_hlayers):
            for j in range(neurons_per_hlayer):
                network[i] = Neuron((i,j))
                
        for j in range(num_results):
            network[neurons_per_hlayer] = Neuron((neurons_per_hlayer, j))
            
            
        

### Para ANN (Implementacion matricial)

In [2]:
import numpy as np
import random

Note: Probably the best way to implement this is not with OOP, but my intuition tells me to start this way, probably I will change it later.


Ok, so after some time trying to figure it out, I already understand the lineal algebra interpretation of neural networks, and my first approach is going to create some classes (OOP). In my analisys, I have identified 4 types of matrix, that i will explain rn:
- Input matrix ($I$)
- Weights matrixs ($W$)
- Hidden layer neurons matrixs ($H$)
- Output layer neurons matrix ($O$)

And, how i am just starting in this, we will start with just binary classification, so the output matrix will be of $1\times1$ (A constant).

And after we create those matrixs, we will start the fastforward, that will be litteraly this math operation:
$I \times W_1 = H_1 \times W_2 = \dots  = H_h \times W_{h+1} = S $.
Here I am excluding the rest of the fast forward steps like the bias and the activation function and all thats stuff.

In [137]:
class Weights:
    def __init__(self, layer, input_neurons, output_neurons):
        self.type = 'Weights matrix'
        self.l = layer
        self.n = input_neurons
        self.m = output_neurons     
        self.temp_matrix = []
        
        for i in range(input_neurons):
            wn = []
            for j in range(output_neurons):
                weight = random.random()
                wn.append(weight)
            self.temp_matrix.append(wn)
            
        self.W = np.matrix(self.temp_matrix)
        
    def show(self):
        print(self.W)

In [49]:
w1 = Weights(1, 2, 4)
print(w1.W)

[[0.08780019 0.30877927 0.70314126 0.28474864]
 [0.50088235 0.35505033 0.55796325 0.32393035]]


In [ ]:
class HLayer:
    def __init__(self, layer, neurons):
        self.layer = layer
        self.type = 'Neurons layer matrix'
        self.H = np.zeros((1, neurons))
        
    def change(self, matrix):
        self.H = matrix
        
    def show(self):
        print(self.H)
        
    def relu(self, x):
        if x < 0:
            return 0
        elif x >= 0:
            return x

    def apply_relu(self):
        for i in self.H[0]:
            if i is self.H[0]: #TODO: Revisar esto
                Hnueva = np.matrix([self.relu(i)])
            else:
                np.append(Hnueva, self.relu(i))
                
        self.H = Hnueva
        


In [138]:
h1 = HLayer(2, 4)
print(h1.H)

h1.change(np.ones((1, 4)))

print(h1.H)

[[0. 0. 0. 0.]]
[[1. 1. 1. 1.]]


In [ ]:
class InputLayer:
    def __init__(self, neurons, len_inp, inp):
        self.n = neurons
        self.type = 'Input layer matrix'
        self.len_inp = len_inp #el tamaño del input
        self.inp = inp #TODO: que hago aca?
        

### Creating the ANN

In [ ]:
def create_ann(len_inp, num_initial_layer, num_hlayers, neurons_per_hlayer, num_results): # For now, I will use binary classification
    l0 = InputLayer(num_initial_layer, len_inp, 0)
    ann = [l0]
    xd = []
    for ilayer in range(num_hlayers):
        inpneu = num_initial_layer if ilayer == 0 else neurons_per_hlayer
        w = Weights(ilayer, inpneu, num_initial_layer)
        ann.append(w)
        
        l = HLayer(ilayer, neurons_per_hlayer)
        ann.append(l)
        
    
    wf = Weights(ilayer, inpneu, 1)
    ann.append(wf)
    
    #TODO: Que hago con la ultima layer?
    ult_layer = 0
    ann.append(ult_layer)
    return ann

In [ ]:
ann = create_ann(3, 2, 4, 4, 1)
c = 0
for i in ann:
    if c == 0:
        c+=1
        continue
    
    if c > len(ann)-2:
        break

    i.show()
    print("\n")
    
    c+=1

[[0.1514157  0.73872285]
 [0.32739352 0.67370883]]


[[0. 0. 0. 0.]]


[[0.35214743 0.21328195]
 [0.34020794 0.693505  ]
 [0.76380712 0.47302079]
 [0.58787525 0.74727255]]


[[0. 0. 0. 0.]]


[[0.51721817 0.62394034]
 [0.78616641 0.68174813]
 [0.6682286  0.80620692]
 [0.73156615 0.37374145]]


[[0. 0. 0. 0.]]


[[0.8720735  0.82909624]
 [0.04825543 0.92486362]
 [0.61745994 0.2594719 ]
 [0.81968388 0.99491556]]


[[0. 0. 0. 0.]]


[[0.17559569]
 [0.28315372]
 [0.66333617]
 [0.060281  ]]




# Training stuff

## Fast Forward

In [ ]:
def forward_propgation(ann):
    i = 0
    while i < len(ann)-1:
        if i % 2 != 0:
            i+=1
            continue
        
        neur = ann[i]
        weig = ann[i+1]
        
        result = np.dot(neur, weig)
        ann[i+2].change(result)
        
        i+=1
        
    res = ann[-1]
    return res

In [111]:
ann = [1,0,1,0,1,0,1,0,1,0,9]
forward_propgation(ann)

1
1
1
1
9


## Backpropagation

## Covolucion

In [ ]:
def covolution(m1, m2): #Deben ser cuadradas
    len_mc = len(m1) - len(m2) + 1
    mehh = [0]*len_mc
    mc = mehh*len_mc
    ci = 0
    cj = 0
    for i,fila in enumerate(m1):
        if i == len(m1) - len(m2): #TODO: Optimizar esto
            break
        for j, columna in enumerate (fila):
            if j == len(m1) - len(m2): #TODO: REVSIAR
                break
            resloc = 0
            for i2 in range(len(m2)):
                for j2 in range(len(m2)):
                    print(type(j))
                    print(type(j2))
                    resloc+=(m1[i+i2][j+j2] * m2[i2][j2])
            mc[ci][cj] = resloc
            cj+=1
        ci+=1
    return mc

In [ ]:
m1 = [[1,6,9,10,2,8],
        [2,5,1,8,4,2],
        [5,7,4,9,10,3],
        [9,8,3,6,7,4],
        [8,6,9,4,7,2],
        [9,10,12,6,9,8]]

m2 = [[1,0,-1],
      [1,0,-1],
      [1,0,-1]]

print(covolution(m1,m2))

## Max pooling